[tool.poetry]
name = "splunk-monitoring"
version = "0.0.3"
description = "Scripts I use for monitoring Splunk-related things"
authors = ["James Hodgkinson <james@terminaloutcomes.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
schedule = "^1.1.0"
click = "^8.1.3"
requests = "^2.28.0"
loguru = "^0.6.0"

[tool.poetry.dev-dependencies]
pylint = "^2.13.9"
pytest = "^7.1.2"
mypy = "^0.961"
black = "^22.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
"splunk-hec-watchdog" = 'splunk_monitoring.hec_watchdog:cli'
"splunk-os-release" = 'splunk_monitoring.os_release:cli'
"splunk-log-handler" = 'splunk_monitoring.loghandler:cli'