[tool.poetry]
name = "splunk-monitoring"
version = "0.0.1"
description = "Scripts I use for monitoring Splunk-related things"
authors = ["James Hodgkinson <james@terminaloutcomes.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
schedule = "^1.1.0"
click = "^8.0.3"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
pylint = "^2.12.2"
pytest = "^6.2.5"
mypy = "^0.931"
black = "^21.12b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
"splunk-hec-watchdog" = 'splunk_monitoring.hec_watchdog:cli'
"splunk-os-release" = 'splunk_monitoring.os_release:cli'
"splunk-log-handler" = 'splunk_monitoring.loghandler:cli'