name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'release.tar'
        type: tar
        #exclusions: '*.git* /*node_modules/* .editorconfig'
        path: ./scripts
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release.tar"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.sha }}, latest